from . import orientation_tuning, contrast_sensitivity,\
        ff_gratings_8orientations_2contrasts,\
        ff_gratings_2orientations_8contrasts,\
        multiStim

GluN3_BlankFirst=ff_gratings_8orientations_2contrasts
GluN3_BlankLast=ff_gratings_8orientations_2contrasts
ff_gratings_2orientations_8contrasts_15repeats=ff_gratings_2orientations_8contrasts
ff_gratings_8orientation_2contrasts_15repeats=ff_gratings_8orientations_2contrasts
ff_gratings_8orientations_2contrasts_15repeats=ff_gratings_8orientations_2contrasts
vision_survey=multiStim
NDNF_protocol=multiStim
